# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 23:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agroquimico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa', models.BooleanField(default=False)),
                ('asesoramientoOtro', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateField(blank=True, default=None, null=True)),
                ('modificado', models.DateField(blank=True, default=None, null=True)),
                ('eliminado', models.DateField(blank=True, default=None, null=True)),
                ('transaccion', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'agroquimico',
            },
        ),
        migrations.CreateModel(
            name='AgroquimicoUsado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('plaga', models.CharField(max_length=50)),
                ('metodo_aplicacion', models.CharField(max_length=50)),
                ('frecuencia_uso', models.CharField(max_length=50)),
                ('creado', models.DateField(blank=True, default=None, null=True)),
                ('modificado', models.DateField(blank=True, default=None, null=True)),
                ('eliminado', models.DateField(blank=True, default=None, null=True)),
                ('transaccion', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'agroquimico_usado',
            },
        ),
        migrations.CreateModel(
            name='AnioConstruccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'anio_construccion',
            },
        ),
        migrations.CreateModel(
            name='Asesoramiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'asesoramiento',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroSiembra', models.IntegerField()),
                ('mesSiembra', models.IntegerField()),
                ('surcos', models.IntegerField()),
                ('distancias', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('eleccionEspecificar', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('especieNueva', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('creado', models.DateField(blank=True, default=None, null=True)),
                ('modificado', models.DateField(blank=True, default=None, null=True)),
                ('eliminado', models.DateField(blank=True, default=None, null=True)),
                ('transaccion', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'cultivo',
            },
        ),
        migrations.CreateModel(
            name='EleccionCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'eleccion_cultivo',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('creado', models.DateField(blank=True, default=None, null=True)),
                ('modificado', models.DateField(blank=True, default=None, null=True)),
                ('eliminado', models.DateField(blank=True, default=None, null=True)),
                ('transaccion', models.CharField(default=None, max_length=50)),
                ('agroquimico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Agroquimico')),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='Encuestado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('nivelCompleto', models.BooleanField(default=False)),
                ('viveEstablecimiento', models.BooleanField(default=False)),
                ('creado', models.DateField(blank=True, default=None, null=True)),
                ('modificado', models.DateField(blank=True, default=None, null=True)),
                ('eliminado', models.DateField(blank=True, default=None, null=True)),
                ('transaccion', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'encuestado',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=45)),
                ('posLatitud', models.FloatField()),
                ('posLongitud', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('regimenOtros', models.CharField(blank=True, max_length=50)),
                ('creado', models.DateField(blank=True, default=None, null=True)),
                ('modificado', models.DateField(blank=True, default=None, null=True)),
                ('eliminado', models.DateField(blank=True, default=None, null=True)),
                ('transaccion', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'establecimiento',
            },
        ),
        migrations.CreateModel(
            name='FactorClimatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'factor_climatico',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esCasado', models.BooleanField()),
                ('tieneHijos', models.BooleanField()),
                ('cantVarones', models.IntegerField(default=0)),
                ('cantMujeres', models.IntegerField(default=0)),
                ('creado', models.DateField(blank=True, default=None, null=True)),
                ('modificado', models.DateField(blank=True, default=None, null=True)),
                ('eliminado', models.DateField(blank=True, default=None, null=True)),
                ('transaccion', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'familia',
            },
        ),
        migrations.CreateModel(
            name='Invernaculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadModulos', models.IntegerField()),
                ('superficieUnitaria', models.IntegerField()),
                ('creado', models.DateField(blank=True, default=None, null=True)),
                ('modificado', models.DateField(blank=True, default=None, null=True)),
                ('eliminado', models.DateField(blank=True, default=None, null=True)),
                ('transaccion', models.CharField(default=None, max_length=50)),
                ('anioContruccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.AnioConstruccion')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Encuesta')),
            ],
            options={
                'db_table': 'invernaculo',
            },
        ),
        migrations.CreateModel(
            name='MaterialEstructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'material_construccion',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='NivelInstruccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nivel_instrucion',
            },
        ),
        migrations.CreateModel(
            name='RegimenTenencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'regimen_tenencia',
            },
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_cultivo',
            },
        ),
        migrations.CreateModel(
            name='TipoProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_produccion',
            },
        ),
        migrations.CreateModel(
            name='TripleLavado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'triple_lavado',
            },
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=50)),
                ('id_entidad', models.IntegerField()),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'updates',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dni', models.CharField(max_length=8)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Operador', 'Operador'), ('Encuestador', 'Encuestador')], max_length=15)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UpdatesFromMobile',
            fields=[
                ('updates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='principal.Updates')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario')),
            ],
            bases=('principal.updates',),
        ),
        migrations.AddField(
            model_name='invernaculo',
            name='materialEstructura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.MaterialEstructura'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='regimenTenencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.RegimenTenencia'),
        ),
        migrations.AddField(
            model_name='encuestado',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Nacionalidad'),
        ),
        migrations.AddField(
            model_name='encuestado',
            name='nivelInstruccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.NivelInstruccion'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='encuestado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.Encuestado'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='establecimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.Establecimiento'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='familia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Familia'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='eleccionCultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.EleccionCultivo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Encuesta'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Especie'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TipoCultivo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipoProducion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TipoProduccion'),
        ),
        migrations.AddField(
            model_name='agroquimicousado',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Encuesta'),
        ),
        migrations.AddField(
            model_name='agroquimico',
            name='asesoramiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Asesoramiento'),
        ),
        migrations.AddField(
            model_name='agroquimico',
            name='factorClimatico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.FactorClimatico'),
        ),
        migrations.AddField(
            model_name='agroquimico',
            name='tripleLavado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TripleLavado'),
        ),
    ]
