# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 02:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agroquimico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa', models.BooleanField(default=False)),
                ('asesoramientoOtro', models.CharField(max_length=50)),
                ('creado', models.DateField(default=None)),
                ('modificado', models.DateField(default=None)),
                ('eliminado', models.DateField(default=None)),
            ],
            options={
                'db_table': 'agroquimico',
            },
        ),
        migrations.CreateModel(
            name='AgroquimicoUsado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('plaga', models.CharField(max_length=50)),
                ('metodo_aplicacion', models.CharField(max_length=50)),
                ('frecuencia_uso', models.CharField(max_length=50)),
                ('creado', models.DateField(default=None)),
                ('modificado', models.DateField(default=None)),
                ('eliminado', models.DateField(default=None)),
            ],
            options={
                'db_table': 'agroquimico_usado',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroSiembra', models.IntegerField()),
                ('mesSiembra', models.IntegerField()),
                ('surcos', models.IntegerField()),
                ('distancias', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('creado', models.DateField(default=None)),
                ('modificado', models.DateField(default=None)),
                ('eliminado', models.DateField(default=None)),
            ],
            options={
                'db_table': 'cultivo',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('creado', models.DateField(default=None)),
                ('modificado', models.DateField(default=None)),
                ('eliminado', models.DateField(default=None)),
                ('agroquimico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Agroquimico')),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='Encuestado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('nivelCompleto', models.BooleanField(default=False)),
                ('viveEstablecimiento', models.BooleanField(default=False)),
                ('creado', models.DateField(default=None)),
                ('modificado', models.DateField(default=None)),
                ('eliminado', models.DateField(default=None)),
            ],
            options={
                'db_table': 'encuestado',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=45)),
                ('posLatitud', models.FloatField()),
                ('posLongitud', models.FloatField()),
                ('foto', models.ImageField(null=True, upload_to='fotos/')),
                ('regimenOtros', models.CharField(blank=True, max_length=50)),
                ('creado', models.DateField(default=None)),
                ('modificado', models.DateField(default=None)),
                ('eliminado', models.DateField(default=None)),
            ],
            options={
                'db_table': 'establecimiento',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esCasado', models.BooleanField()),
                ('tieneHijos', models.BooleanField()),
                ('cantVarones', models.IntegerField()),
                ('cantMujeres', models.IntegerField()),
                ('creado', models.DateField(default=None)),
                ('modificado', models.DateField(default=None)),
                ('eliminado', models.DateField(default=None)),
            ],
            options={
                'db_table': 'familia',
            },
        ),
        migrations.CreateModel(
            name='Invernaculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadModulos', models.IntegerField()),
                ('superficieUnitaria', models.IntegerField()),
                ('creado', models.DateField(default=None)),
                ('modificado', models.DateField(default=None)),
                ('eliminado', models.DateField(default=None)),
            ],
            options={
                'db_table': 'invernaculo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dni', models.CharField(max_length=8)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Operador', 'Operador'), ('Encuestador', 'Encuestador')], max_length=15)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='anioconstruccion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asesoramiento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eleccioncultivo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='factorclimatico',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materialestructura',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nivelinstruccion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regimentenencia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipocultivo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoproduccion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='triplelavado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='anioconstruccion',
            table='anio_construccion',
        ),
        migrations.AlterModelTable(
            name='asesoramiento',
            table='asesoramiento',
        ),
        migrations.AlterModelTable(
            name='eleccioncultivo',
            table='eleccion_cultivo',
        ),
        migrations.AlterModelTable(
            name='especie',
            table='especie',
        ),
        migrations.AlterModelTable(
            name='factorclimatico',
            table='factor_climatico',
        ),
        migrations.AlterModelTable(
            name='materialestructura',
            table='material_construccion',
        ),
        migrations.AlterModelTable(
            name='nacionalidad',
            table='nacionalidad',
        ),
        migrations.AlterModelTable(
            name='nivelinstruccion',
            table='nivel_instrucion',
        ),
        migrations.AlterModelTable(
            name='regimentenencia',
            table='regimen_tenencia',
        ),
        migrations.AlterModelTable(
            name='tipocultivo',
            table='tipo_cultivo',
        ),
        migrations.AlterModelTable(
            name='tipoproduccion',
            table='tipo_produccion',
        ),
        migrations.AlterModelTable(
            name='triplelavado',
            table='triple_lavado',
        ),
        migrations.AddField(
            model_name='invernaculo',
            name='anioContruccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.AnioConstruccion'),
        ),
        migrations.AddField(
            model_name='invernaculo',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Encuesta'),
        ),
        migrations.AddField(
            model_name='invernaculo',
            name='materialEstructura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.MaterialEstructura'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='regimenTenencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.RegimenTenencia'),
        ),
        migrations.AddField(
            model_name='encuestado',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Nacionalidad'),
        ),
        migrations.AddField(
            model_name='encuestado',
            name='nivelInstruccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.NivelInstruccion'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='encuestado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Encuestado'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Establecimiento'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Familia'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='eleccionCultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.EleccionCultivo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Encuesta'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Especie'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TipoCultivo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipoProducion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TipoProduccion'),
        ),
        migrations.AddField(
            model_name='agroquimicousado',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Encuesta'),
        ),
        migrations.AddField(
            model_name='agroquimico',
            name='asesoramiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Asesoramiento'),
        ),
        migrations.AddField(
            model_name='agroquimico',
            name='factorClimatico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.FactorClimatico'),
        ),
        migrations.AddField(
            model_name='agroquimico',
            name='tripleLavado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TripleLavado'),
        ),
    ]
