# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_establecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='posLatitud',
            field=models.FloatField(max_length=45),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='posLongitud',
            field=models.FloatField(max_length=45),
        ),
    ]
