# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20171027_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='posLatitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='posLongitud',
            field=models.FloatField(),
        ),
    ]
