# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20171027_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/establecimientos'),
        ),
    ]
