# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20171124_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='agroquimico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Agroquimico'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='encuestado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.Encuestado'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='establecimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.Establecimiento'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='familia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Familia'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario'),
        ),
    ]
