# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20171124_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=50)),
                ('id_entidad', models.IntegerField()),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'updates',
            },
        ),
    ]
