# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_establecimiento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/img/establecimientos/'),
        ),
    ]
