# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='especieNueva',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
