# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_cultivo_especienueva'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatesFromMobile',
            fields=[
                ('updates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='principal.Updates')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario')),
            ],
            bases=('principal.updates',),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='eleccionEspecificar',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cantMujeres',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cantVarones',
            field=models.IntegerField(default=0),
        ),
    ]
