# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20171211_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario'),
        ),
    ]
