# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_encuestador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_operador',
            field=models.BooleanField(default=False),
        ),
    ]
