# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20171213_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anioconstruccion',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asesoramiento',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='eleccioncultivo',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='especie',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='factorclimatico',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='materialestructura',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nivelinstruccion',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='regimentenencia',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipocultivo',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoproduccion',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='triplelavado',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
