# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20171107_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_administrador',
            new_name='es_administrador',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_encuestador',
            new_name='es_encuestador',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_operador',
            new_name='es_operador',
        ),
    ]
