# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20171216_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agroquimico',
            name='transaccion',
        ),
        migrations.RemoveField(
            model_name='agroquimicousado',
            name='transaccion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='transaccion',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='transaccion',
        ),
        migrations.RemoveField(
            model_name='encuestado',
            name='transaccion',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='transaccion',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='transaccion',
        ),
        migrations.RemoveField(
            model_name='invernaculo',
            name='transaccion',
        ),
    ]
