# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20171216_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invernaculo',
            old_name='anioContruccion',
            new_name='anioConstruccion',
        ),
    ]
