# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20171107_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_encuestador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_operador',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Operador', 'Operador'), ('Encuestador', 'Encuestador')], default='SOME STRING', max_length=15),
        ),
    ]
