# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20171216_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivo',
            old_name='tipoProducion',
            new_name='tipoProduccion',
        ),
    ]
