# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('principal', '0014_auto_20171108_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
