# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_auto_20171117_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
